version: "3"
services:
  frontend:
    image: mic_sample:frontend
    container_name: mic_frontend
    volumes:
      - "${SRC}/frontend/:/var/www"
      - "/var/www/node_modules"
    environment:
      - NUXT_HOST=0.0.0.0
    ports:
    - "8000:8000"
  backend:
    image: mic_sample:backend
    container_name: mic_backend
    tty: true
    volumes:
      - "${SRC}/backend:/var/www"
    ports:
      - "8080:8080"
    command:
      "python server.py"
